### ISSUE TITLE
Protection against spoofed widget usage

### ISSUE THREAD

**Issue by mattpass** [BTCPrivate/btcp-widget#5]
The widget code can be taken and used on any website, because it is entirely client side JS.

However, we can at least track it's usage. The first time it's installed on merchant website, we can note the merchant host/domain name and also the IP. If this changes/changes regularly, it can alert us

**Comment by daniel-farina** [comment]
I can confirm the widget currently performs validation on the site. If you try using the widget with our website as the API the way it's currently setup it will not allow a domain not configured with the widget.
